# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-18 08:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='DataPictureMapping',
        ),
        migrations.DeleteModel(
            name='TagMapping',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='access',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='chime_plan',
            new_name='qro_plan',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 9, 18, 8, 5, 18, 26478, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
