# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20160418_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.BigIntegerField(default=342342),
            preserve_default=False,
        ),
    ]
