# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20160605_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='original_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
