# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20160422_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ango', models.CharField(max_length=100)),
                ('facebook_id', models.BigIntegerField()),
            ],
        ),
    ]
