# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='ango',
            new_name='password',
        ),
    ]
